name: ayuborneo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_esc_pos_utils: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  flutter_pos_printer_platform_image_3: ^1.1.2
  go_router: ^9.0.3
  http: ^1.1.0
  path_provider: ^2.0.15
  pdf_render: ^1.4.0
  permission_handler: ^10.4.3
  printing: ^5.11.0
  syncfusion_flutter_pdf: ^22.2.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
